### ISSUE TITLE
How can we use this to deploy to Heroku?

### ISSUE THREAD

**Issue by NaseebullahSafi** [iampava/steal-like-a-dev#1]
First of, thank you for sharing an insight into how one can configure webpack to run React without any toolchain. We appreciate your wisdom.

Question is, I'm trying to deploy React app (without CRA) to Heroku, but I'm finding it hard to deploy this.

Heroku requires `start` script within package.json. Since we have only the following scripts:
```json
"scripts": {
    "start": "rm -rf build/ && webpack-dev-server --env.mode development --hot",
    "build": "rm -rf build/ && webpack --env.mode production"
}
```

How can I build for production and then deploy to Heroku?

**Comment by iampava** [comment]
Hey, and glad to hear it :)

Actually I do have a React app configured like in this repo which is deployed to Heroku. In my `package.json` I don't have a `start` script, instead I have a `server.js` file in the root of the folder which is entry point for my Node.js server. 

```json
"clear": "rm -rf dist/",
"webpack": "webpack",
"webpack-dev-server": "webpack-dev-server",
"dev": "npm run webpack-dev-server -- --env.mode development --hot",
"prod": "npm run clear && npm run webpack -- --env.mode production"
```

It seems this way, Heroku will default to running the server from that file.

So, how I deploy the app (https://devdrive.io) is like this:
1. `npm run prod`
2. `git push heroku master`

Hope that helps. Cheers!
